services:
  fast_pr_database :
    image: postgres
    volumes:
    - pgdata:/var/lib/postgresql/
    environment:
      POSTGRES_USER: app_user
      POSTGRES_DB: app_db
      POSTGRES_PASSWORD: app_password
    ports:
    - "5432:5432"
    

  fast_pr_app:
    image: fast_pr_app
    entrypoint: ./entrypoint.sh
    build: .
    ports:
    - "8000:8000"
    depends_on:
      - fast_pr_database
    env_file:
    - .env 

volumes:
 pgdata: