"""timestamp 2

Revision ID: f443fadefcea
Revises: 8f1a2ab8aaef
Create Date: 2026-04-28 20:21:24.988285

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f443fadefcea'
down_revision: Union[str, Sequence[str], None] = '8f1a2ab8aaef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'users', ['username'])
    op.drop_column('users', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', sa.VARCHAR(), nullable=False))
    op.drop_constraint(None, 'users', type_='unique')
    # ### end Alembic commands ###
